from PyQt5.QtWidgets import QApplication, QGraphicsView, QStyleFactory
from PyQt5.QtCore import Qt 

import sys
if sys.platform == 'win32':
    # Windows-specific adjustments
    from ctypes import windll
    windll.shcore.SetProcessDpiAwareness(1)  # Для правильного масштабирования

import a_YAML_2_Graph
import methods
import os

# Autogenerated with DRAKON Editor 1.31

def a_Main():
    #item 135
    s_Error,  \
    s_File_Name, \
    s_Diagram_Code = diagram_Code_From_Command_Line()
    #item 144
    if s_Error == "":
        pass
    else:
        #item 146
        warning_Show(s_Error)
        #item 147
        s_File_Name = file_Name_temp()
        #item 139
        s_Diagram_Code = silhouette_Code()
        #item 143
        state = diagram_Show( \
        		s_file_name, \
        		s_Diagram_Code)
    #item 148
    b_Exit = False
    
    while not b_Exit:
    	b_Exit = user_Actions()


def a_Main_OLD():
    #item 99
    # Тема светлая
    
    QApplication.setStyle("Fusion")
    
    QApplication.setPalette(
    	QStyleFactory.create("Fusion")
    		.standardPalette()
    )
    #item 68
    """Основная функция приложения"""
    
    app = QApplication([])
    
    s_Error = ""
    
    # главное окно 
    window = methods.create_main_window()
    while True:
        #item 104
        action, s_User_Choice = command_line_action_file_name()
        #item 1050001
        if action == file_create:
            #item 74
            # TODO создать файл пустой диаграммы
            #item 77
            s_Code = methods.file_New_Create()
            #item 78
            if s_Code == "":
                #item 83
                s_Error = \
                "Ошибка создания нового файла"
            else:
                #item 101
                # Панель инструментов
                toolbar = methods.create_toolbar(window)
                
                # Список функций
                a1_Functions = methods.yaml_Functions(s_Code)
                
                function_dock, filter_input, function_list = methods.create_function_list(window, a1_Functions)
                
                scene, view = methods.create_diagram_canvas(window)
                
                # Настройка и отображение
                methods.setup_layout(window, toolbar, function_dock, view)
                #item 98
                # TODO удалить 
                scene = a_YAML_2_Graph.code_2_Graph(s_Code)
                
                # TODO сделать
                # s_Function_Name = взять имя функции из опция
                # или листа функций
                # s_Function_Code = yaml_Function_Code(s_Code, s_Function_Name) 
                # scene = a_YAML_2_Graph.function_2_Graph()
                
                view = QGraphicsView(scene)
                
                window.setCentralWidget(view)
                #item 76
                window.show()
                #item 75
                sys.exit(app.exec_())
            break
        else:
            pass
        #item 1050002
        if action == file_open:
            #item 60
            if os.path.exists(s_User_Choice):
                #item 64
                with open(s_User_Choice, 'r', encoding='utf-8') as file:
                    s_Code = file.read()
                #item 65
                if methods.yaml_Validate(s_Code):
                    #item 101
                    # Панель инструментов
                    toolbar = methods.create_toolbar(window)
                    
                    # Список функций
                    a1_Functions = methods.yaml_Functions(s_Code)
                    
                    function_dock, filter_input, function_list = methods.create_function_list(window, a1_Functions)
                    
                    scene, view = methods.create_diagram_canvas(window)
                    
                    # Настройка и отображение
                    methods.setup_layout(window, toolbar, function_dock, view)
                    #item 98
                    # TODO удалить 
                    scene = a_YAML_2_Graph.code_2_Graph(s_Code)
                    
                    # TODO сделать
                    # s_Function_Name = взять имя функции из опция
                    # или листа функций
                    # s_Function_Code = yaml_Function_Code(s_Code, s_Function_Name) 
                    # scene = a_YAML_2_Graph.function_2_Graph()
                    
                    view = QGraphicsView(scene)
                    
                    window.setCentralWidget(view)
                    #item 76
                    window.show()
                    #item 75
                    sys.exit(app.exec_())
                    break
                else:
                    pass
                #item 82
                s_Error = \
                "Код диаграммы плохой"
            else:
                #item 63
                # TOOD 
                # сообщение Файла НЕТ
        else:
            #item 100
            s_User_Choice = methods.options_FileName()
            #item 32
            if s_User_Choice == '':
                #item 54
                # Диалог выбор файла или действия
                
                s_User_Choice = methods.file_Choice([])
                #item 470001
                if s_User_Choice == "File create":
                    #item 74
                    # TODO создать файл пустой диаграммы
                    #item 77
                    s_Code = methods.file_New_Create()
                    #item 78
                    if s_Code == "":
                        #item 83
                        s_Error = \
                        "Ошибка создания нового файла"
                    else:
                        #item 101
                        # Панель инструментов
                        toolbar = methods.create_toolbar(window)
                        
                        # Список функций
                        a1_Functions = methods.yaml_Functions(s_Code)
                        
                        function_dock, filter_input, function_list = methods.create_function_list(window, a1_Functions)
                        
                        scene, view = methods.create_diagram_canvas(window)
                        
                        # Настройка и отображение
                        methods.setup_layout(window, toolbar, function_dock, view)
                        #item 98
                        # TODO удалить 
                        scene = a_YAML_2_Graph.code_2_Graph(s_Code)
                        
                        # TODO сделать
                        # s_Function_Name = взять имя функции из опция
                        # или листа функций
                        # s_Function_Code = yaml_Function_Code(s_Code, s_Function_Name) 
                        # scene = a_YAML_2_Graph.function_2_Graph()
                        
                        view = QGraphicsView(scene)
                        
                        window.setCentralWidget(view)
                        #item 76
                        window.show()
                        #item 75
                        sys.exit(app.exec_())
                    break
                else:
                    pass
                #item 470002
                if s_User_Choice == "File open dialog":
                    #item 70
                    s_User_Choice = methods.file_Open_Dialog()
                    #item 71
                    if s_User_Choice is None:
                        pass
                    else:
                        #item 60
                        if os.path.exists(s_User_Choice):
                            #item 64
                            with open(s_User_Choice, 'r', encoding='utf-8') as file:
                                s_Code = file.read()
                            #item 65
                            if methods.yaml_Validate(s_Code):
                                #item 101
                                # Панель инструментов
                                toolbar = methods.create_toolbar(window)
                                
                                # Список функций
                                a1_Functions = methods.yaml_Functions(s_Code)
                                
                                function_dock, filter_input, function_list = methods.create_function_list(window, a1_Functions)
                                
                                scene, view = methods.create_diagram_canvas(window)
                                
                                # Настройка и отображение
                                methods.setup_layout(window, toolbar, function_dock, view)
                                #item 98
                                # TODO удалить 
                                scene = a_YAML_2_Graph.code_2_Graph(s_Code)
                                
                                # TODO сделать
                                # s_Function_Name = взять имя функции из опция
                                # или листа функций
                                # s_Function_Code = yaml_Function_Code(s_Code, s_Function_Name) 
                                # scene = a_YAML_2_Graph.function_2_Graph()
                                
                                view = QGraphicsView(scene)
                                
                                window.setCentralWidget(view)
                                #item 76
                                window.show()
                                #item 75
                                sys.exit(app.exec_())
                                break
                            else:
                                pass
                            #item 82
                            s_Error = \
                            "Код диаграммы плохой"
                        else:
                            #item 63
                            # TOOD 
                            # сообщение Файла НЕТ
                else:
                    #item 470003
                    if s_User_Choice == "Exit":
                        #item 81
                        s_Error = \
                        "Пользователь выбрал Выход"
                        break
                    else:
                        pass
                    #item 60
                    if os.path.exists(s_User_Choice):
                        #item 64
                        with open(s_User_Choice, 'r', encoding='utf-8') as file:
                            s_Code = file.read()
                        #item 65
                        if methods.yaml_Validate(s_Code):
                            #item 101
                            # Панель инструментов
                            toolbar = methods.create_toolbar(window)
                            
                            # Список функций
                            a1_Functions = methods.yaml_Functions(s_Code)
                            
                            function_dock, filter_input, function_list = methods.create_function_list(window, a1_Functions)
                            
                            scene, view = methods.create_diagram_canvas(window)
                            
                            # Настройка и отображение
                            methods.setup_layout(window, toolbar, function_dock, view)
                            #item 98
                            # TODO удалить 
                            scene = a_YAML_2_Graph.code_2_Graph(s_Code)
                            
                            # TODO сделать
                            # s_Function_Name = взять имя функции из опция
                            # или листа функций
                            # s_Function_Code = yaml_Function_Code(s_Code, s_Function_Name) 
                            # scene = a_YAML_2_Graph.function_2_Graph()
                            
                            view = QGraphicsView(scene)
                            
                            window.setCentralWidget(view)
                            #item 76
                            window.show()
                            #item 75
                            sys.exit(app.exec_())
                            break
                        else:
                            pass
                        #item 82
                        s_Error = \
                        "Код диаграммы плохой"
                    else:
                        #item 63
                        # TOOD 
                        # сообщение Файла НЕТ
            else:
                #item 60
                if os.path.exists(s_User_Choice):
                    #item 64
                    with open(s_User_Choice, 'r', encoding='utf-8') as file:
                        s_Code = file.read()
                    #item 65
                    if methods.yaml_Validate(s_Code):
                        #item 101
                        # Панель инструментов
                        toolbar = methods.create_toolbar(window)
                        
                        # Список функций
                        a1_Functions = methods.yaml_Functions(s_Code)
                        
                        function_dock, filter_input, function_list = methods.create_function_list(window, a1_Functions)
                        
                        scene, view = methods.create_diagram_canvas(window)
                        
                        # Настройка и отображение
                        methods.setup_layout(window, toolbar, function_dock, view)
                        #item 98
                        # TODO удалить 
                        scene = a_YAML_2_Graph.code_2_Graph(s_Code)
                        
                        # TODO сделать
                        # s_Function_Name = взять имя функции из опция
                        # или листа функций
                        # s_Function_Code = yaml_Function_Code(s_Code, s_Function_Name) 
                        # scene = a_YAML_2_Graph.function_2_Graph()
                        
                        view = QGraphicsView(scene)
                        
                        window.setCentralWidget(view)
                        #item 76
                        window.show()
                        #item 75
                        sys.exit(app.exec_())
                        break
                    else:
                        pass
                    #item 82
                    s_Error = \
                    "Код диаграммы плохой"
                else:
                    #item 63
                    # TOOD 
                    # сообщение Файла НЕТ


def b_YAML_2_Graph(s_Code):
    pass

if __name__ == "__main__":
    a_Main()
