from PyQt5.QtWidgets import (QApplication, QGraphicsView, QGraphicsScene, 
                           QMainWindow)
from PyQt5.QtCore import QRectF

import sys
if sys.platform == 'win32':
    # Windows-specific adjustments
    from ctypes import windll
    windll.shcore.SetProcessDpiAwareness(1)  # Для правильного масштабирования

import methods
import os

# Autogenerated with DRAKON Editor 1.31

def main():
    """Основная функция приложения"""
    app = QApplication([])
    
    # главное окно 
    window, scene = create_main_window()
    
    window.show()
    
    _next_item_ = 32
    while True:
        if _next_item_ == 32:
            if len(sys.argv) > 1:
                _next_item_ = 54
            else:
                _next_item_ = 60
    
        elif _next_item_ == 60:
            if os.path.exists(s_User_Choice):
                #item 64
                with open(s_User_Choice, 'r', encoding='utf-8') as file:
                    s_Code = file.read()
                _next_item_ = 65
            else:
                #item 63
                # TOOD 
                # сообщение Файла НЕТ
                _next_item_ = 54
    
        elif _next_item_ == 65:
            if code_Good(s_Code):
                return None
            else:
                _next_item_ = 54
    
        elif _next_item_ == 54:
            s_User_Choice = methods.file_Choice([])
            _next_item_ = 470001
    
        elif _next_item_ == 470001:
            if (s_User_Choice == "File create") or (not ((s_User_Choice == "File open") or (not (s_User_Choice == "Exit")))):
                return None
            else:
                _next_item_ = 60
    

if __name__ == "__main__":
    main()
