from PyQt5.QtWidgets import QApplication  
#from PyQt5.QtCore    import QRectF

import sys
if sys.platform == 'win32':
    # Windows-specific adjustments
    from ctypes import windll
    windll.shcore.SetProcessDpiAwareness(1)  # Для правильного масштабирования

import methods
import os

from drakon_parser   import parse_drakon_file
from drakon_renderer import DrakonRenderer


# Autogenerated with DRAKON Editor 1.31

def main():
    """Основная функция приложения"""
    app = QApplication([])
    
    # главное окно 
    window, scene = methods.create_main_window()
    
    _next_item_ = 32
    while True:
        if _next_item_ == 32:
            if len(sys.argv) > 1:
                #item 69
                s_User_Choice = sys.argv[1]
                _next_item_ = 60
            else:
                _next_item_ = 54
    
        elif _next_item_ == 54:
            s_User_Choice = methods.file_Choice([])
            _next_item_ = 470001
    
        elif _next_item_ == 470001:
            if s_User_Choice == "File create":
                #item 74
                # TODO создать файл пустой диаграммы
                _next_item_ = 77
            else:
                _next_item_ = 470002
    
        elif _next_item_ == 470002:
            if s_User_Choice == "File open":
                #item 70
                s_User_Choice = methods.file_Open_Dialog()
                _next_item_ = 71
            else:
                _next_item_ = 470003
    
        elif _next_item_ == 71:
            if s_User_Choice is None:
                _next_item_ = 54
            else:
                _next_item_ = 60
    
        elif _next_item_ == 470003:
            if s_User_Choice == "Exit":
                return None
            else:
                _next_item_ = 60
    
        elif _next_item_ == 60:
            if os.path.exists(s_User_Choice):
                #item 64
                with open(s_User_Choice, 'r', encoding='utf-8') as file:
                    s_Code = file.read()
                _next_item_ = 65
            else:
                #item 63
                # TOOD 
                # сообщение Файла НЕТ
                _next_item_ = 54
    
        elif _next_item_ == 65:
            if methods.code_Good(s_Code):
                _next_item_ = 77
            else:
                _next_item_ = 54
    
        elif _next_item_ == 77:
            try:
                diagram_data = parse_drakon_file(s_User_Choice)
                renderer = DrakonRenderer()
                scene = renderer.render_diagram(diagram_data)
                
                # Обновляем отображение
                window.centralWidget().layout().itemAt(0).widget().setScene(scene)
            except Exception as e:
                print(f"Ошибка отрисовки: {str(e)}")
            _next_item_ = 76
    
        elif _next_item_ == 76:
            window.show()
            _next_item_ = 75
    
        elif _next_item_ == 75:
            app.exec_()
            return None
    

if __name__ == "__main__":
    main()
